export const projects = [
  {
    name: 'Google Home Page',
    desc: 'My first project at HTML and CSS.',
    languages: {
      html: 'picture of html5',
      css: 'picture of css3',
    },
    month: 11,
    year: 2018,
    complete: true,
  },
  {
    name: 'Google Search Page',
    desc: 'My second project at HTML and CSS.',
    languages: {
      html: 'picture of html5',
      css: 'picture of css3',
    },
    tools: [],
    month: 11,
    year: 2018,
    complete: true,
  },
  {
    name: 'Just Dodge, blue boy',
    desc: 'Experiment with MelonJS framework',
    languages: {
      melon: 'picture of javascript',
    },
    month: 3,
    year: 2019,
    complete: true,
  },
  {
    name: 'Game of Thrones Themed Forum',
    desc: 'A forum with a synopsis-wiki',
    languages: {
      react: 'pic of react',
      rails: 'pic of rails',
      postgresql: 'pic of postgres',
      sass: 'pic of sass',
      bootstrap: 'pic of bootstrap',
    },
    month: 4,
    year: 2019,
    complete: true,
  },
  {
    name: 'Ani-Shelf',
    desc: 'Inspired by Ani-List and Ani-Chart webpages',
    tools: {
      react: 'pic of react',
      rails: 'pic of rails',
      postgresql: 'pic of postgres',
      css: 'pic of css',
    },
    month: 3,
    year: 2019,
    complete: true,
  },
  {
    name: 'Simon.gg',
    desc: 'Inspired by op.gg',
    tools: {
      rails: 'pic of rails',
      postgresql: 'pic of postgres',
      css: 'pic of css',
    },
    month: 2,
    year: 2019,
    complete: true,
  },
  {
    name: 'Achiever (In-Progress)',
    desc: 'App that searches your Steam Achievements.',
    tools: {
      react: 'pic of react',
      node: 'pic of node',
      express: 'pic of express',
      sass: 'pic of sass',
    },
    month: 5,
    year: 2019,
    complete: false,
  },
  {
    name: 'Pokemon Search',
    desc: 'something something',
    languages: {
      javascript: 'pic of js',
    },
    month: 5,
    year: 2019,
    complete: true,
  },
  {
    name: 'Natours',
    desc: 'Advanced CSS',
    languages: {
      html: 'picture of html5',
      sass: 'picture of sass',
    },
    month: 12,
    year: 2018,
    complete: true,
  },
  {
    name: 'Nexter',
    desc: 'Advanced CSS using Flexbox',
    languages: {
      html: 'picture of html5',
      sass: 'picture of sass',
    },
    month: 12,
    year: 2018,
    complete: true,
  },
  {
    name: 'Trillo',
    desc: 'Advanced CSS using grids',
    languages: {
      html: 'picture of html5',
      sass: 'picture of sass',
    },
    month: 12,
    year: 2018,
    complete: true,
  },
  {
    name: 'Pig Game',
    desc: 'Aasdasd',
    languages: ['Javascript'],
    month: 3,
    year: 2019,
    complete: true,
  },
  {
    name: 'Budgety',
    desc: 'asdasd',
    languages: ['Javascript'],
    month: 3,
    year: 2019,
    complete: true,
  },
  {
    name: 'Forkify',
    desc: 'asdasd',
    languages: ['Javascript'],
    month: 3,
    year: 2019,
    complete: true,
  },
  {
    name: 'Weather App',
    desc: 'Basic Weather App using DarkSky API',
    languages: {
      javascript: 'picture of javascript',
    },
    tools: {
      handlebars: 'pic of handlebars',
      node: 'pic of node',
      express: 'pic of express',
    },
    month: 5,
    year: 2019,
    complete: true,
  },
  {
    name: 'Notes App',
    desc: 'Basic To-Do List/Notes Apps',
    languages: {
      javascript: 'picture of javascript',
    },
    tools: {
      node: 'pic of node',
    },
    month: 5,
    year: 2019,
    complete: true,
  },
  {
    name: 'Task Manager (In Progress)',
    desc: 'Task Manager',
    languages: {
      javascript: 'picture of javascript',
    },
    tools: {
      node: 'pic of node',
      express: 'pic of express',
    },
    month: 5,
    year: 2019,
    complete: false,
  },
];
